---

- name: deploy systemd configuration
  template: src=consul-template.systemd.j2 dest=/lib/systemd/system/consul-template.service owner=root group=root mode=0644
  notify: reload-systemd

- name: make systemd symlink
  file: src=/lib/systemd/system/consul-template.service dest=/etc/systemd/system/multi-user.target.wants/consul-template.service owner=root group=root state=link

- meta: flush_handlers

- name: ensure service is started
  service: name=consul-template state=started
